$pdflatex = 'xelatex -interaction=nonstopmode -synctex=1 %O %S';
$xelatex = 'xelatex -interaction=nonstopmode -synctex=1 %O %S';
$bibtex = 'bibtex %O %B';
$biber = 'biber %O %B';
$pdf_mode = 5;  # xelatex
$out_dir = '.';
$aux_dir = '.';
